### PR TITLE
Fix the URL for an individual continent

### PR DESCRIPTION
**Pull request by troyjfarrell**
The example project uses the code field as Continent's primary key.

# Pull requests

Thank you for submitting a contribution to Django Translations.

Please ensure the following steps have been taken:

## All changes

- [x] Is this contribution for a known issue in the issues? If so mention it.
- [x] Is there a task for this contribution in the project board? If so mention it.

## Documentation changes

- [x] Have you built the documentation?
- [x] Have you run the documentation tests?

### CODE REVIEW

**Comment by bbmokhtari** [comment]
I'm closing this pull request, cause it does _not_ do what it says it does.

regarding the change to support postgresql I'm checking your other PR ( #83 ) out.

**Comment by troyjfarrell** [comment]
Thank you @bbmokhtari.  The first change in the PR d9f6da1 does solve this problem.  GitHub did us the favor of adding the other changes to the PR.  If you would like to fix this bug, then please cherry pick the first change.

**Comment by bbmokhtari** [comment]
I already committed that line manually in the repo since I had closed this PR. **I am very sorry!**

But regarding your other PR #83 :
I merged it into a branch called `postgresql-support` and rebased it to `master` branch.
I opened a new PR #95 from that rebased branch.

There are a couple of things that have to be done (which I'm currently adding to your commits):
1. Make the current tests pass: [runs/11429415892](https://github.com/bbmokhtari/django-translations/actions/runs/11429415892)
2. Add databases (`mysql`, `postgres`, etc.) `services` to the Github Actions Workflow in order to  actually make sure the changes will work on all databases without breaking other people's systems which are already dependent on the library (in case they upgrade)

When I merge that one your code will be merged alongside it too.

**Comment by bbmokhtari** [comment]
Forgot to mention you in the message above @troyjfarrell

**Pull request closed without merging**
