### PR TITLE
support django 4

### PR DESCRIPTION
**Pull request by urm8**
# Pull requests
Fix import error for django 4.*
https://github.com/bbmokhtari/django-translations/issues/81
Please ensure the following steps have been taken:

## All changes

- [X] Is this contribution for a known issue in the issues? If so mention it.
- [ ] Is there a task for this contribution in the project board? If so mention it. ??? 

## Code changes

- [X] Have you run the unit tests on the project before submitting the contribution?
- [] Have you added the appropriate unit tests for your contribution to the project?
- [] Have you added the appropriate documentation for your contribution to the project?
- [X] Have you styled your code properly based on the contribution guidelines?

## Documentation changes

- [-] Have you built the documentation?
- [-] Have you run the documentation tests?

## Note:
Please ensure that once the PR is submitted, you check Travis CI for build issues and submit an update to your PR as soon as possible.

### CODE REVIEW

**Comment by urm8** [comment]
@bbmokhtari can you merge it pls ?

**Comment by PeterJCLaw** [comment]
@bbmokhtari just wondering if there's anything that you feel needs to doing to this PR before it can merge? I'd like to help if I can?

**Comment by bbmokhtari** [comment]
I would prefer that this change would accompany an added test matrix in Travis CI configuration for Django 4. But I just noticed that Travis CI has ended its unlimited support for open source projects. I will merge this for now, even though it lacks proper testing and assurance.

I think we need to look for a free CI solution for this project.

**Comment by PeterJCLaw** [comment]
@bbmokhtari Thanks for merging this. Unfortunately it looks like this isn't quite enough to get Django 4 fully working. I've a PR at https://github.com/bbmokhtari/django-translations/pull/89 which adds CI using GitHub Actions and a follow-on at https://github.com/PeterJCLaw/django-translations/pull/2 (placeholder that I can open once the GHA PR is merged) which fixes the reset of the Django 4 support.

**Pull request merged**
